#ifndef DLLOMAUIKOMPONENTTI_GLOBAL_H
#define DLLOMAUIKOMPONENTTI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLOMAUIKOMPONENTTI_LIBRARY)
#  define DLLOMAUIKOMPONENTTISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLOMAUIKOMPONENTTISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLOMAUIKOMPONENTTI_GLOBAL_H
