#ifndef DLLDATABASECOMPONENT_GLOBAL_H
#define DLLDATABASECOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLDATABASECOMPONENT_LIBRARY)
#  define DLLDATABASECOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLDATABASECOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLDATABASECOMPONENT_GLOBAL_H
